### ISSUE TITLE
Awesome project! Do you consider alternative touch friendly UI? 

### ISSUE THREAD

**Issue by penk** [InnovateAsterisk/Raspberry-Pi-Tablet#2]
Hey man, great work! I'm working on a Pi (CM-based) tablet myself, https://cutiepi.io/ 

We made a touch friendly shell for Raspbian, would you like to try it on your project? https://github.com/cutiepi-io/cutiepi-shell

**Comment by InnovateAsterisk** [comment]
Touch based (or touch first) UI was one of the primary objectives with this project - however I have not had the time to experiment with alternatives to Raspbian... yet. I'll take a look.

**Comment by penk** [comment]
Understood, good luck with the project, it's a cool one! :-) 

We've also found a way to make virtual keyboard working across Gtk+ and Qt apps on top of Raspbian's PIXEL environment, through IM module. Please ping me anytime if you want to test or try prebuilt binary.
